version: '2.1'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=taste-waf
    ports:
      - 5432:5432
  spring-boot:
    image: satoshiyamamoto/spring-boot
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=db
